### ISSUE TITLE
Linux send keys example?

### ISSUE THREAD

**Issue by gianniskarmas** [kujirahand/node-sendkeys-js#1]
I can't manage to send key presses on Linux.
Works great on Win, Mac though.

Can you please give me an example?
I just need to send 'left', 'right'.

Many Thanks.

**Comment by ledenis** [comment]
@gianniskarmas for arrow keys in Linux, there is a bug, see https://github.com/kujirahand/node-sendkeys-js/pull/2

Also, have you to installed `xdotool`?

```
sudo apt-get install xdotool
```
