### ISSUE TITLE
command key on mac

### ISSUE THREAD

**Issue by craftycram** [kujirahand/node-sendkeys-js#7]
Hey, how can I send the COMMAND key on MacOS?  
I wanna send `Control + D` on Windows and `Command + D` on MacOS.  
Using `process.plattform` I decide between both plattforms and sending `^d` already works on Windows.  
Kind regards, Marc

**Comment by ledenis** [comment]
I don't have a Mac, but I think you can send `Command + D` with:

```
sendkeys.sendKeys('&d')
```
because I see that `&` is `Command` according to: `const metaChars = {'+': 'shift', '^': 'control', '%': 'alt', '&': 'command'}`  in https://github.com/kujirahand/node-sendkeys-js/blob/master/platform/darwin.js#L52

**Comment by craftycram** [comment]
Awesome thank you that worked! Didn't think about looking for keycodes in the code.  
Guessed that they're defined on the system. My mistake 😅

**Comment by ledenis** [comment]
No problem :+1:
